### ISSUE TITLE
Issue on docs

### ISSUE THREAD

**Issue by wzying58** [Chainlit/docs#86]
Path: /get-started/pure-python

Error with the command below:

$ chainlit run app.py -w
2023-12-17 22:41:45 - Your app is available at http://localhost:8000
message async handler error
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\socketio\async_server.py", line 545, in _handle_connect
    success = await self._trigger_event(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\socketio\async_server.py", line 631, in _trigger_event
    ret = await handler(*args)
                ^^^^^^^^^^^^^^
TypeError: connect() missing 1 required positional argument: 'auth'

**Comment by willydouhard** [comment]
Is it strictly running the documentation's code? What version of Chainlit are you using?

**Comment by ModEnter** [comment]
This issue is not reproductible with the example code ; furthermore a lot of changes have been made to the framework and the documentation.
